version: "3.7"
services:
  php:
    build: ./docker/php-fpm
    container_name: php
    ports:
      - "9000:9001"
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached

  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached
